version: "3"

services:

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes: 
      - ./server:/app
    # ports: 
    #   - "3001:3001"
    tty: true
    networks: 
      - my-net

  react-app:
    build: 
      context: ./blog-app
      dockerfile: Dockerfile
    volumes: 
      - ./blog-app:/usr/src/app/
    stdin_open: true
    # ports: 
    #   - "3000:3000"
    tty: true
    networks: 
      - my-net
    depends_on: 
      - server
      
networks:
  my-net:
    driver: bridge
